Repository uOttawa-Collabs/CSI4106-Fall-2023, pull requests merged in 2023-10, with the labels that each got.

#5 Finish Genetic Algorithm
  Assignment 1/.gitignore
  Assignment 1/CSI4106_A1.ipynb
Labels: Pull Request: Ready for Review

#6 Fixed Simulated Annealing
  Assignment 1/CSI4106_A1.ipynb
Labels: Pull Request: Ready for Merge, Pull Request: Ready for Review

#12 Fixed Encoding and Finished Traning for Two Models
  Assignment 2/CSI4106_A2.ipynb
Labels: Pull Request: Ready for Review

#14 Data Analysis & Conclusion
  Assignment 2/CSI4106_A2.ipynb
Labels: Pull Request: Work in Progress

#15 Add description for training & evaluation function
  Assignment 2/CSI4106_A2.ipynb
Labels: Pull Request: Ready for Review
